version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "/app/temporal/roadrunner-worker"
  env:
    - XDEBUG_SESSION: 0

http:
  address: :80
  #max_request_size: 256
  middleware: [ "static", "headers", "gzip" ]
  uploads:
    dir: /tmp
    forbid: [ ".php", ".exe", ".bat", ".sh" ]
  headers:
    response:
      X-Powered-By: RoadRunner
  ssl:
    # force redirect to https connection
    redirect: true
    # custom https port (default 443)
    port: 443
    # ssl cert
    cert: server.crt
    # ssl private key
    key: server.key
    # rootCA certificate path
    rootCa: root.crt
  static:
    dir: "/app/public"
    forbid: [".htaccess", ".php", ".sql", ".config", "php_errors.log"]
    calculate_etag: false
    weak: false
    allow: [ "" ]
    request:
      input: "custom-header"
    response:
      output: "output-header"
  pool:
    num_workers: 3
    max_jobs: 64
    debug: false

temporal:
  address: temporal:7233
  activities:
    num_workers: 6

reload:
  interval: 1s
  patterns: [".php", ".yaml"]
  services:
    http:
      recursive: true
      dirs: [ "/app/app" ]
    temporal:
      recursive: true
      dirs: [ "/app/app" ]

status:
  address: roadrunner:2114
