version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "/app/temporal/roadrunner-worker"
  env:
    - XDEBUG_SESSION: 1

http:
  address: :80
  #max_request_size: 256
  middleware: [ "static", "headers", "gzip" ]
  uploads:
    dir: /tmp
    forbid: [ ".php", ".exe", ".bat", ".sh" ]
  headers:
    response:
      X-Powered-By: RoadRunner
  ssl:
    address: :443
    key: "/app/ssl/localhost-key.pem"
    cert: "/app/ssl/localhost.pem"
    root_ca: "/app/ssl/localhost.pem"
    #client_auth_type: require_and_verify_client_cert
  static:
    dir: "/app/public"
    forbid: [".htaccess", ".php", ".sql", ".config", "php_errors.log"]
    calculate_etag: false
    weak: false
    allow: [ "" ]
    request:
      input: "custom-header"
    response:
      output: "output-header"
  pool:
    num_workers: 2
    allocate_timeout: 30s
    max_jobs: 64
    debug: false

temporal:
  address: temporal:7233
  activities:
    num_workers: 6

reload:
  interval: 1s
  patterns: [".php", ".yaml"]
  services:
    http:
      recursive: true
      dirs: [ "/app/app" ]
    temporal:
      recursive: true
      dirs: [ "/app/app" ]

status:
  address: roadrunner:2114
